Factorial:
	java -jar ../3/interpreter/pgi.jar < Factorial.microIR

Temp:
	java -jar ../3/interpreter/pgi.jar < Temp.microIR

BinarySearch:
	java -jar ../3/interpreter/pgi.jar < BinarySearch.microIR

BinaryTree:
	java -jar ../3/interpreter/pgi.jar < BinaryTree.microIR

BubbleSort:
	java -jar ../3/interpreter/pgi.jar < BubbleSort.microIR

LinearList: 
	java -jar ../3/interpreter/pgi.jar < LinearList.microIR

LinearSearch:
	java -jar ../3/interpreter/pgi.jar < LinearSearch.microIR

QuickSort:
	java -jar ../3/interpreter/pgi.jar < QuickSort.microIR

TreeVisitor:
	java -jar ../3/interpreter/pgi.jar < TreeVisitor.microIR

BS:
	java -jar ../3/interpreter/pgi.jar < BS.microIR